FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y \
        build-essential \
        gcc \
        g++ \
        gcc-multilib \
        g++-multilib \
        libc6-dev \
        libc6-dev-i386 \
        libc6-dbg \
        make \
        gdb \
        valgrind \
        nasm \
        man-db \
        manpages \
        manpages-dev \
        file \
        nano \
        vim \
        less \
        procps \
        git \
        wget \
        curl \
        zip \
        unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces
